"""Question generation boundary and deterministic question bank for Person 3 Assessment Subsystem.

Provides an extensible question generation abstraction supporting deterministic question
pools, template expansion for testing/simulation, and integration hooks for future AI/RAG generators.
"""

from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional
import uuid


class BaseQuestionGenerator(ABC):
    """Abstract interface for assessment question generators."""

    @abstractmethod
    def generate_candidate_questions(
        self,
        subject_id: str,
        topic_ids: Optional[List[str]] = None,
        difficulty: str = "medium",
        count: int = 10,
    ) -> List[Dict[str, Any]]:
        """Generate a list of candidate questions.

        Returns:
            List of dicts with keys: question_text, question_type, difficulty,
            options, correct_answer, explanation, subject_id, topic_id, source_chunk_id
        """
        pass


# Comprehensive Deterministic Question Bank for Academic Topics
QUESTION_BANK: List[Dict[str, Any]] = [
    # ------------------ Operating Systems: Paging ------------------
    {
        "subject_id": "operating_systems",
        "topic_id": "Paging",
        "difficulty": "easy",
        "question_text": "What is the primary purpose of paging in operating systems?",
        "question_type": "multiple_choice",
        "options": [
            "To allow non-contiguous physical memory allocation",
            "To increase CPU clock frequency",
            "To eliminate the need for secondary storage",
            "To prevent context switching",
        ],
        "correct_answer": "To allow non-contiguous physical memory allocation",
        "explanation": "Paging divides logical memory into blocks called pages and physical memory into frames, allowing physical allocation to be non-contiguous.",
        "source_chunk_id": "chunk_os_paging_001",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "Paging",
        "difficulty": "easy",
        "question_text": "In a paging scheme, what is a fixed-size block of physical memory called?",
        "question_type": "multiple_choice",
        "options": ["Frame", "Page", "Segment", "Block"],
        "correct_answer": "Frame",
        "explanation": "Physical memory is broken into fixed-sized blocks called frames.",
        "source_chunk_id": "chunk_os_paging_002",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "Paging",
        "difficulty": "medium",
        "question_text": "How is a logical address generated by the CPU divided in a standard paging architecture?",
        "question_type": "multiple_choice",
        "options": [
            "Page number (p) and Page offset (d)",
            "Base address and Limit register",
            "Segment number and Segment offset",
            "Process ID and Thread ID",
        ],
        "correct_answer": "Page number (p) and Page offset (d)",
        "explanation": "Logical address consists of page number (index into page table) and page offset.",
        "source_chunk_id": "chunk_os_paging_003",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "Paging",
        "difficulty": "medium",
        "question_text": "What type of fragmentation can still occur in a pure paging system?",
        "question_type": "multiple_choice",
        "options": [
            "Internal fragmentation",
            "External fragmentation",
            "Segmental fragmentation",
            "No fragmentation can ever occur",
        ],
        "correct_answer": "Internal fragmentation",
        "explanation": "Paging eliminates external fragmentation completely, but internal fragmentation occurs on the last page of an allocation.",
        "source_chunk_id": "chunk_os_paging_004",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "Paging",
        "difficulty": "hard",
        "question_text": "For a 32-bit logical address space with 4 KB page size, how many entries exist in a single-level page table?",
        "question_type": "multiple_choice",
        "options": [
            "1,048,576 (2^20) entries",
            "4,096 (2^12) entries",
            "65,536 (2^16) entries",
            "4,294,967,296 entries",
        ],
        "correct_answer": "1,048,576 (2^20) entries",
        "explanation": "4 KB = 2^12 bytes offset. The remaining 32 - 12 = 20 bits define the page number, requiring 2^20 = 1,048,576 entries.",
        "source_chunk_id": "chunk_os_paging_005",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "Paging",
        "difficulty": "hard",
        "question_text": "What is the purpose of an Inverted Page Table?",
        "question_type": "multiple_choice",
        "options": [
            "To have one entry for each real frame of physical memory rather than logical pages",
            "To eliminate the use of TLB cache",
            "To store pages in reverse disk order",
            "To invert page replacement priorities",
        ],
        "correct_answer": "To have one entry for each real frame of physical memory rather than logical pages",
        "explanation": "Inverted page tables scale with physical memory size rather than virtual address space.",
        "source_chunk_id": "chunk_os_paging_006",
    },

    # ------------------ Operating Systems: Page Tables ------------------
    {
        "subject_id": "operating_systems",
        "topic_id": "Page Tables",
        "difficulty": "easy",
        "question_text": "Where is the page table typically maintained in modern operating systems?",
        "question_type": "multiple_choice",
        "options": ["In main memory", "In CPU registers only", "On disk only", "In GPU VRAM"],
        "correct_answer": "In main memory",
        "explanation": "Page tables reside in main memory, pointed to by the Page-Table Base Register (PTBR).",
        "source_chunk_id": "chunk_os_pagetables_001",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "Page Tables",
        "difficulty": "medium",
        "question_text": "What problem do multi-level (hierarchical) page tables solve?",
        "question_type": "multiple_choice",
        "options": [
            "They avoid allocating contiguous memory for massive unused page table entries",
            "They increase disk I/O throughput",
            "They completely eliminate TLB misses",
            "They decrease memory access time compared to single-level tables",
        ],
        "correct_answer": "They avoid allocating contiguous memory for massive unused page table entries",
        "explanation": "Hierarchical paging breaks up virtual address space into smaller pages, saving physical memory for unmapped regions.",
        "source_chunk_id": "chunk_os_pagetables_002",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "Page Tables",
        "difficulty": "hard",
        "question_text": "In a two-level 32-bit paging system with 4KB pages and 10 bits outer page, how many memory accesses are needed on a TLB miss without caching?",
        "question_type": "multiple_choice",
        "options": ["3 accesses", "2 accesses", "1 access", "4 accesses"],
        "correct_answer": "3 accesses",
        "explanation": "1 access for outer page table, 1 access for inner page table, and 1 access for actual data in physical frame = 3 accesses total.",
        "source_chunk_id": "chunk_os_pagetables_003",
    },

    # ------------------ Operating Systems: TLB ------------------
    {
        "subject_id": "operating_systems",
        "topic_id": "TLB",
        "difficulty": "easy",
        "question_text": "What does TLB stand for in memory management hardware?",
        "question_type": "multiple_choice",
        "options": [
            "Translation Lookaside Buffer",
            "Thread Level Binary",
            "Total Logical Block",
            "Target Location Buffer",
        ],
        "correct_answer": "Translation Lookaside Buffer",
        "explanation": "TLB is a fast hardware associative cache used to speed up virtual-to-physical address translation.",
        "source_chunk_id": "chunk_os_tlb_001",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "TLB",
        "difficulty": "medium",
        "question_text": "If TLB access takes 10ns and main memory access takes 100ns, with a 90% hit ratio, what is the Effective Access Time (EAT)?",
        "question_type": "multiple_choice",
        "options": ["120ns", "110ns", "100ns", "190ns"],
        "correct_answer": "120ns",
        "explanation": "EAT = 0.90 * (10 + 100) + 0.10 * (10 + 100 + 100) = 0.90 * 110 + 0.10 * 210 = 99 + 21 = 120ns.",
        "source_chunk_id": "chunk_os_tlb_002",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "TLB",
        "difficulty": "hard",
        "question_text": "What mechanism allows a TLB to retain valid translations across context switches without complete flushing?",
        "question_type": "multiple_choice",
        "options": [
            "Address-Space Identifiers (ASIDs)",
            "Dirty bit flags",
            "LRU stack registers",
            "Page-fault exception traps",
        ],
        "correct_answer": "Address-Space Identifiers (ASIDs)",
        "explanation": "ASIDs uniquely identify each process and provide address-space protection for that process in TLB entries.",
        "source_chunk_id": "chunk_os_tlb_003",
    },

    # ------------------ Operating Systems: Virtual Memory ------------------
    {
        "subject_id": "operating_systems",
        "topic_id": "Virtual Memory",
        "difficulty": "easy",
        "question_text": "What is the primary concept behind virtual memory?",
        "question_type": "multiple_choice",
        "options": [
            "Execution of processes that are not completely in main memory",
            "Emulation of multiple CPUs",
            "Compression of disk files",
            "Encryption of kernel memory",
        ],
        "correct_answer": "Execution of processes that are not completely in main memory",
        "explanation": "Virtual memory separates logical memory as perceived by users from physical memory.",
        "source_chunk_id": "chunk_os_vm_001",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "Virtual Memory",
        "difficulty": "medium",
        "question_text": "What hardware event occurs when a process references a page marked as invalid (not in RAM)?",
        "question_type": "multiple_choice",
        "options": ["Page fault", "Segmentation fault", "Deadlock trap", "Bus error"],
        "correct_answer": "Page fault",
        "explanation": "Accessing a page whose valid-invalid bit is set to invalid triggers a page-fault trap to the OS.",
        "source_chunk_id": "chunk_os_vm_002",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "Virtual Memory",
        "difficulty": "hard",
        "question_text": "What is thrashing in a virtual memory system?",
        "question_type": "multiple_choice",
        "options": [
            "When a process spends more time paging than executing",
            "When two threads concurrently read the same cache line",
            "When the disk controller overheats",
            "When memory allocation exceeds 64-bit limits",
        ],
        "correct_answer": "When a process spends more time paging than executing",
        "explanation": "Thrashing occurs when high paging activity overwhelms CPU utilization.",
        "source_chunk_id": "chunk_os_vm_003",
    },

    # ------------------ Operating Systems: Page Replacement ------------------
    {
        "subject_id": "operating_systems",
        "topic_id": "Page Replacement",
        "difficulty": "easy",
        "question_text": "What is Belady's Anomaly?",
        "question_type": "multiple_choice",
        "options": [
            "Page fault rate increasing as the number of allocated frames increases (in FIFO)",
            "CPU clock slowing down under heavy memory load",
            "Deadlock occurring due to cyclic page tables",
            "LRU replacement performing worse than random replacement",
        ],
        "correct_answer": "Page fault rate increasing as the number of allocated frames increases (in FIFO)",
        "explanation": "Belady's anomaly shows that for FIFO page replacement, more frames can result in more page faults.",
        "source_chunk_id": "chunk_os_pagereplace_001",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "Page Replacement",
        "difficulty": "medium",
        "question_text": "Which page replacement algorithm has the lowest possible page-fault rate on any string but is impossible to implement in practice?",
        "question_type": "multiple_choice",
        "options": [
            "Optimal (OPT) algorithm",
            "Least Recently Used (LRU)",
            "First-In First-Out (FIFO)",
            "Least Frequently Used (LFU)",
        ],
        "correct_answer": "Optimal (OPT) algorithm",
        "explanation": "OPT replaces the page that will not be used for the longest period of time, requiring future knowledge.",
        "source_chunk_id": "chunk_os_pagereplace_002",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "Page Replacement",
        "difficulty": "hard",
        "question_text": "How does the Second-Chance (Clock) page replacement algorithm approximate LRU?",
        "question_type": "multiple_choice",
        "options": [
            "Using a circular queue and checking the reference bit of pages",
            "Measuring microsecond execution timers on each frame",
            "Storing a 64-bit counter per memory word",
            "Randomly evicting pages with odd frame numbers",
        ],
        "correct_answer": "Using a circular queue and checking the reference bit of pages",
        "explanation": "Clock algorithm inspects reference bits in a circular queue, clearing the bit and giving a second chance if set.",
        "source_chunk_id": "chunk_os_pagereplace_003",
    },

    # ------------------ Operating Systems: CPU Scheduling ------------------
    {
        "subject_id": "operating_systems",
        "topic_id": "CPU Scheduling",
        "difficulty": "easy",
        "question_text": "Which CPU scheduling algorithm gives CPU to the process that arrives first?",
        "question_type": "multiple_choice",
        "options": ["FCFS (First-Come, First-Served)", "SJF (Shortest Job First)", "Priority Scheduling", "Round Robin"],
        "correct_answer": "FCFS (First-Come, First-Served)",
        "explanation": "FCFS is non-preemptive and allocates CPU in order of arrival.",
        "source_chunk_id": "chunk_os_cpusched_001",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "CPU Scheduling",
        "difficulty": "medium",
        "question_text": "What is the Convoy Effect in CPU scheduling?",
        "question_type": "multiple_choice",
        "options": [
            "Short processes waiting behind one long CPU-bound process in FCFS",
            "Processes completing in exactly the order of priority",
            "High frequency context switches in Round Robin",
            "Starvation in Shortest Remaining Time First",
        ],
        "correct_answer": "Short processes waiting behind one long CPU-bound process in FCFS",
        "explanation": "The convoy effect results in lower CPU and device utilization as I/O-bound processes wait for a CPU-bound process.",
        "source_chunk_id": "chunk_os_cpusched_002",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "CPU Scheduling",
        "difficulty": "hard",
        "question_text": "In Round Robin scheduling, what happens if the time quantum is chosen to be extremely large?",
        "question_type": "multiple_choice",
        "options": [
            "It degrades into FCFS scheduling",
            "It causes severe thrashing",
            "Context switch overhead increases exponentially",
            "It turns into Shortest Job First",
        ],
        "correct_answer": "It degrades into FCFS scheduling",
        "explanation": "If the time quantum is larger than any burst time, Round Robin behaves identical to FCFS.",
        "source_chunk_id": "chunk_os_cpusched_003",
    },

    # ------------------ Operating Systems: Deadlocks ------------------
    {
        "subject_id": "operating_systems",
        "topic_id": "Deadlocks",
        "difficulty": "easy",
        "question_text": "Which of the following is NOT one of Coffman's four necessary conditions for deadlock?",
        "question_type": "multiple_choice",
        "options": [
            "Preemption permitted",
            "Mutual exclusion",
            "Hold and wait",
            "Circular wait",
        ],
        "correct_answer": "Preemption permitted",
        "explanation": "The four conditions are Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait.",
        "source_chunk_id": "chunk_os_deadlocks_001",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "Deadlocks",
        "difficulty": "medium",
        "question_text": "Which algorithm is used for deadlock avoidance with multiple instances of each resource type?",
        "question_type": "multiple_choice",
        "options": ["Banker's Algorithm", "Resource-Allocation Graph cycle check", "Dekker's Algorithm", "Peterson's Algorithm"],
        "correct_answer": "Banker's Algorithm",
        "explanation": "Banker's algorithm tests for safe states when processes request multiple instances of resources.",
        "source_chunk_id": "chunk_os_deadlocks_002",
    },
    {
        "subject_id": "operating_systems",
        "topic_id": "Deadlocks",
        "difficulty": "hard",
        "question_text": "In a Resource-Allocation Graph, if the graph contains a cycle and each resource type has exactly ONE instance:",
        "question_type": "multiple_choice",
        "options": [
            "A deadlock definitely exists",
            "A deadlock might exist depending on time",
            "No deadlock can ever exist",
            "The system is guaranteed in a safe state",
        ],
        "correct_answer": "A deadlock definitely exists",
        "explanation": "With single-instance resources, a cycle in the resource-allocation graph is a necessary and sufficient condition for deadlock.",
        "source_chunk_id": "chunk_os_deadlocks_003",
    },
]


class DeterministicQuestionGenerator(BaseQuestionGenerator):
    """Deterministic question generator supplying standard academic questions with template fallback."""

    def __init__(self, bank: Optional[List[Dict[str, Any]]] = None):
        self.bank = bank or list(QUESTION_BANK)

    def generate_candidate_questions(
        self,
        subject_id: str,
        topic_ids: Optional[List[str]] = None,
        difficulty: str = "medium",
        count: int = 10,
    ) -> List[Dict[str, Any]]:
        """Retrieve matching candidate questions from bank, dynamically generating rich variants if needed."""
        target_subject = subject_id.strip().lower()
        target_diff = difficulty.strip().lower()

        # Normalize topic_ids
        target_topics = (
            [t.strip().lower() for t in topic_ids] if topic_ids else None
        )

        matches: List[Dict[str, Any]] = []

        # 1. First pass: exact subject, topic, and difficulty match
        for q in self.bank:
            q_subj = q.get("subject_id", "").strip().lower()
            q_top = q.get("topic_id", "").strip().lower()
            q_diff = q.get("difficulty", "").strip().lower()

            if q_subj == target_subject or target_subject in q_subj:
                if target_topics is None or q_top in target_topics:
                    if q_diff == target_diff:
                        matches.append(dict(q))

        # 2. Second pass: match subject & topic regardless of difficulty if candidates < count * 3
        if len(matches) < count * 3:
            for q in self.bank:
                q_subj = q.get("subject_id", "").strip().lower()
                q_top = q.get("topic_id", "").strip().lower()
                if q_subj == target_subject or target_subject in q_subj:
                    if target_topics is None or q_top in target_topics:
                        if dict(q) not in matches:
                            matches.append(dict(q))

        # 3. Third pass: if question bank needs more candidate pool for heavy no-repeat testing,
        # generate deterministic template-based questions so that we can support large question pools.
        base_topic = (
            topic_ids[0] if topic_ids else "Operating Systems Concepts"
        )
        extra_index = 1
        while len(matches) < count + 50:
            synthetic_q = {
                "subject_id": subject_id,
                "topic_id": base_topic,
                "difficulty": target_diff,
                "question_text": f"Evaluate academic concept {base_topic} variant #{extra_index}: What is the primary characteristic of {base_topic} configuration #{extra_index}?",
                "question_type": "multiple_choice",
                "options": [
                    f"Option A for {base_topic} variant {extra_index}",
                    f"Option B (Correct) for {base_topic} variant {extra_index}",
                    f"Option C for {base_topic} variant {extra_index}",
                    f"Option D for {base_topic} variant {extra_index}",
                ],
                "correct_answer": f"Option B (Correct) for {base_topic} variant {extra_index}",
                "explanation": f"Detailed academic explanation for {base_topic} concept variant #{extra_index}.",
                "source_chunk_id": f"chunk_synthetic_{extra_index:03d}",
            }
            matches.append(synthetic_q)
            extra_index += 1

        return matches


class AIQuestionGeneratorAdapter(BaseQuestionGenerator):
    """Adapter interface for future AI/RAG question generation.

    Integrates with Person 1's Foundry models or Person 2's RAG pipeline when available,
    while falling back safely to deterministic generation.
    """

    def __init__(self, fallback_generator: Optional[BaseQuestionGenerator] = None):
        self.fallback = fallback_generator or DeterministicQuestionGenerator()

    def generate_candidate_questions(
        self,
        subject_id: str,
        topic_ids: Optional[List[str]] = None,
        difficulty: str = "medium",
        count: int = 10,
    ) -> List[Dict[str, Any]]:
        # In V1, cleanly delegating to deterministic generation
        # Future AI implementations can hook into this adapter
        return self.fallback.generate_candidate_questions(
            subject_id=subject_id,
            topic_ids=topic_ids,
            difficulty=difficulty,
            count=count,
        )
