import { useMemo, useState } from 'react';
import { BookOpen, Check, Clock3, Plus, Search, Sparkles, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../context/AppContext';

export default function Courses(){
 const {courses,addCourse,removeCourse,pushToast,subjects,addSubject,deleteSubject}=useApp(); const navigate=useNavigate(); const [q,setQ]=useState(''); const [category,setCategory]=useState('All'); const [selected,setSelected]=useState<string|null>(null);
 const categories=['All',...Array.from(new Set(courses.map(c=>c.category)))]; const filtered=useMemo(()=>courses.filter(c=>(category==='All'||c.category===category)&&(`${c.name} ${c.code} ${c.category}`.toLowerCase().includes(q.toLowerCase()))),[courses,q,category]);
 const course=selected?courses.find(c=>c.id===selected):null;
 const enroll=(id:string)=>{addCourse(id); const c=courses.find(x=>x.id===id); if(c){ if(!subjects.some(s=>s.name===c.name)){addSubject({id:c.id,name:c.name,fullName:c.name,documentsCount:0,progress:c.progress,topicsCompleted:Math.round(c.topics.length*c.progress/100),totalTopics:c.topics.length,color:c.color,tag:c.code});} pushToast(`${c.name} added to My Subjects`,'success'); }};
 return <div className="page-stack">
  <div className="page-hero"><div><div className="eyebrow">COURSE LIBRARY</div><h1>Learn something new.</h1><p>Pre-built courses give you a structured starting point. Add any course to personalize your dashboard, planner and progress.</p></div><button className="btn primary" onClick={()=>navigate('/knowledge')}><Sparkles size={16}/>Build from my material</button></div>
  <div className="toolbar"><div className="search-box"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search courses, subjects or codes..."/></div><div className="chip-row">{categories.map(c=><button key={c} className={`filter-chip ${category===c?'active':''}`} onClick={()=>setCategory(c)}>{c}</button>)}</div></div>
  <div className="course-grid">{filtered.map(c=><div className="course-card" key={c.id}><div className="course-accent" style={{background:c.color}}/><div className="course-card-body"><div className="course-icon" style={{background:`${c.color}18`,color:c.color}}><BookOpen size={20}/></div><div className="course-meta"><span>{c.code}</span><span>{c.level}</span></div><h3>{c.name}</h3><p>{c.description}</p><div className="topic-row">{c.topics.slice(0,3).map(t=><span key={t}>{t}</span>)}{c.topics.length>3&&<span>+{c.topics.length-3}</span>}</div><div className="course-footer"><span><Clock3 size={14}/>{c.estimatedHours}h</span><span>{c.progress}% progress</span></div><div className="progress-track"><span style={{width:`${c.progress}%`,background:c.color}}/></div><div className="course-actions"><button className="btn secondary" onClick={()=>setSelected(c.id)}>View course</button>{c.enrolled?<button className="btn subtle" onClick={()=>{removeCourse(c.id);const linked=subjects.find(s=>s.name===c.name);if(linked)deleteSubject(linked.id);pushToast('Course removed from My Subjects','info')}}><Check size={15}/>Added</button>:<button className="btn primary" onClick={()=>enroll(c.id)}><Plus size={15}/>Add to My Subjects</button>}</div></div></div>)}</div>
  {!filtered.length&&<div className="empty-state"><BookOpen size={30}/><h3>No courses found</h3><p>Try another search or category.</p></div>}
  {course&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal wide" onClick={e=>e.stopPropagation()}><button className="icon-button modal-close" onClick={()=>setSelected(null)}><X size={18}/></button><div className="eyebrow">{course.code} · {course.level}</div><h2>{course.name}</h2><p className="muted">{course.description}</p><h3>What you'll learn</h3><div className="topic-list">{course.topics.map((t,i)=><div key={t}><span>{i+1}</span>{t}</div>)}</div><div className="modal-actions"><button className="btn secondary" onClick={()=>{setSelected(null);navigate('/assessment')}}>Create quiz</button>{course.enrolled?<button className="btn subtle" onClick={()=>{removeCourse(course.id);const linked=subjects.find(s=>s.name===course.name);if(linked)deleteSubject(linked.id);setSelected(null);pushToast('Course removed','info')}}>Remove from My Subjects</button>:<button className="btn primary" onClick={()=>{enroll(course.id);setSelected(null)}}><Plus size={15}/>Add to My Subjects</button>}</div></div></div>}
 </div>
}
