import { useMemo, useState } from 'react';
import { Search, Send, MessageCircle, Mail, ExternalLink, CheckCircle2 } from 'lucide-react';
import HeroHeader from '../components/ui/HeroHeader';
import SectionHeader from '../components/ui/SectionHeader';
import Modal from '../components/ui/Modal';
import { HELP_CATEGORIES, SYSTEM_STATUS_ITEMS, useApp } from '../context/AppContext';

const TAGS=['Upload Notes','Create Quiz','Study Planner','Account & Login','AI Assistant','Data & Privacy'];
const FAQ=[
 ['How do I upload study material?','Open Knowledge, choose Upload Material, select a PDF, DOCX, PPTX or TXT file and assign a subject.'],
 ['How are AI notes generated?','The frontend prepares the document and requested note type. Your Azure AI integration will process the content and return the generated notes.'],
 ['How do I make a quiz?','Use Assessment to generate a quiz from a topic, document or AI note.'],
 ['Can I edit my notes?','Yes. AI notes are editable and can be renamed, updated or deleted.'],
];
export default function HelpSupport(){
 const {pushToast}=useApp(); const [q,setQ]=useState(''); const [resultsOpen,setResultsOpen]=useState(false); const [topic,setTopic]=useState<string|null>(null); const [contact,setContact]=useState<'support'|'chat'|'email'|null>(null); const [feedback,setFeedback]=useState(false);
 const results=useMemo(()=>FAQ.filter(([t,d])=>`${t} ${d}`.toLowerCase().includes(q.toLowerCase())),[q]);
 return <div className="page-stack"><HeroHeader tag="HELP & SUPPORT" title={<>We're Here to <span className="accent">Help.</span></>} subtitle="Find answers, troubleshoot features, and send feedback without leaving AcadAssist." image="/assets/header_help_support.png" />
  <div className="grid grid-cols-1 xl:grid-cols-[1fr_320px] gap-6"><div>
   <div className="card mb-6"><h3 className="font-bold text-sm">Search Help Center</h3><p className="text-xs text-[var(--color-text-muted)] mb-4">Search guides and troubleshooting steps.</p><div className="flex gap-2"><div className="flex-1 search-box"><Search size={14}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search help..."/></div><button className="btn primary" onClick={()=>setResultsOpen(true)}>Search</button></div><div className="flex flex-wrap gap-2 mt-3">{TAGS.map(t=><button key={t} className="filter-chip" onClick={()=>{setQ(t);setResultsOpen(true)}}>{t}</button>)}</div></div>
   <SectionHeader icon="📖" title="Browse Help Topics" action="View All" onAction={()=>setResultsOpen(true)}/><p className="text-xs text-[var(--color-text-muted)] mb-4">Explore practical guides and feature explanations.</p>
   <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">{HELP_CATEGORIES.map((cat,i)=><button key={i} className="card text-left hover:shadow-md" onClick={()=>setTopic(cat.title)}><div className="text-2xl mb-2">{cat.icon==='calendar'?'📅':cat.icon==='cpu'?'🤖':cat.icon==='settings'?'⚙️':cat.icon==='bar-chart-2'?'📊':cat.icon==='folder'?'📁':'🧭'}</div><b className="text-xs">{cat.title}</b><p className="text-[.65rem] text-[var(--color-text-muted)] mt-1">{cat.description}</p><span className="text-xs text-[var(--color-green-accent)]">Open guide →</span></button>)}</div>
   <div className="card"><div className="flex items-center gap-2 mb-3"><CheckCircle2 size={18} className="text-green-600"/><b className="text-sm">Frequently asked questions</b></div>{FAQ.map(([t,d])=><button key={t} className="w-full text-left py-3 border-b border-[var(--color-border-light)] last:border-0" onClick={()=>setTopic(t)}><b className="text-xs">{t}</b><p className="text-[.65rem] text-[var(--color-text-muted)] mt-1 line-clamp-1">{d}</p></button>)}</div>
  </div><div>
   <SectionHeader icon="✉️" title="Get in Touch"/><div className="card mb-6">{[{icon:<Send size={15}/>,label:'Send a Support Request',desc:'Create a support ticket.',key:'support' as const},{icon:<MessageCircle size={15}/>,label:'Live Chat (Beta)',desc:'Start a support chat.',key:'chat' as const},{icon:<Mail size={15}/>,label:'Email Us',desc:'support@acadassist.app',key:'email' as const}].map(x=><button key={x.key} className="w-full flex items-center gap-3 py-3 text-left border-b last:border-0 border-[var(--color-border-light)]" onClick={()=>setContact(x.key)}><span className="w-8 h-8 rounded-lg bg-[var(--color-green-light)] dark:bg-[var(--color-card-border)] text-[var(--color-green-accent)] flex items-center justify-center">{x.icon}</span><span className="flex-1"><b className="text-xs">{x.label}</b><small className="block text-[.6rem] text-[var(--color-text-muted)]">{x.desc}</small></span><ExternalLink size={14}/></button>)}</div>
   <SectionHeader icon="🟢" title="System Status" action="View Status" onAction={()=>setTopic('System Status')}/><div className="card mb-6"><b className="text-xs">All Systems Operational</b>{SYSTEM_STATUS_ITEMS.map(s=><div key={s.name} className="flex justify-between py-2"><span className="text-xs">{s.name}</span><span className="text-xs text-green-600">{s.status}</span></div>)}</div>
   <div className="card"><b className="text-sm">Give Feedback</b><p className="text-xs text-[var(--color-text-muted)] my-2">Report a bug, suggest a feature or tell us what you like.</p><button className="btn secondary w-full" onClick={()=>setFeedback(true)}>Share Feedback <Send size={12}/></button></div>
  </div></div>
  <Modal open={resultsOpen} onClose={()=>setResultsOpen(false)} title="Help Center" subtitle={q?`Results for “${q}”`:'Common AcadAssist questions.'}>{results.length?results.map(([t,d])=><button key={t} className="w-full text-left card mb-2" onClick={()=>setTopic(t)}><b className="text-sm">{t}</b><p className="text-xs text-[var(--color-text-muted)] mt-1">{d}</p></button>):<div className="empty-state"><Search size={24}/><h3>No results</h3><p>Try “upload”, “quiz”, “planner”, or “AI assistant”.</p></div>}</Modal>
  <Modal open={!!topic} onClose={()=>setTopic(null)} title={topic||''}><p className="text-sm text-[var(--color-text-body)]">{topic==='System Status'?'All configured frontend services are available. Azure service health will be shown here once the backend integration is connected.':FAQ.find(x=>x[0]===topic)?.[1]||`This guide explains ${topic}. Use the related feature and follow the on-screen actions. If something fails, send a support request with the page name and error message.`}</p><div className="modal-actions"><button className="btn primary" onClick={()=>{setTopic(null);pushToast('Guide marked as helpful')}}>Helpful</button></div></Modal>
  <Modal open={!!contact} onClose={()=>setContact(null)} title={contact==='support'?'Support Request':contact==='chat'?'Live Chat':'Email Support'}>{contact==='email'?<p className="text-sm">Email <b>support@acadassist.app</b> with your issue and include screenshots when possible.</p>:<><label>Subject<input className="input" placeholder="What do you need help with?"/></label><label>Message<textarea className="textarea" rows={5} placeholder="Describe the issue or request..."/></label><div className="modal-actions"><button className="btn primary" onClick={()=>{setContact(null);pushToast('Support request saved for backend submission')}}>Send request</button></div></>}</Modal>
  <Modal open={feedback} onClose={()=>setFeedback(false)} title="Share feedback"><label>Type<select className="select full"><option>Feature request</option><option>Bug report</option><option>General feedback</option></select></label><label>Feedback<textarea className="textarea" rows={5} placeholder="Tell us what you think..."/></label><div className="modal-actions"><button className="btn primary" onClick={()=>{setFeedback(false);pushToast('Thanks — your feedback was recorded')}}>Submit feedback</button></div></Modal>
 </div>
}
